import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, ImagePlus } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/events/new")({head:()=>({meta:[{title:"Create an event — SYNC"},{name:"description",content:"Create a real-world event with its own private SYNC Zone."},{property:"og:title",content:"Create an event — SYNC"},{property:"og:description",content:"Bring the right people together with a SYNC Zone."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:NewEvent});
function NewEvent(){const{user}=Route.useRouteContext();const[name,setName]=useState("");const[venue,setVenue]=useState("");const[description,setDescription]=useState("");const[type,setType]=useState("community");const[starts,setStarts]=useState("");const[ends,setEnds]=useState("");const[radius,setRadius]=useState("200");const[isPublic,setPublic]=useState(true);const[cover,setCover]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function create(){if(!name||!starts||!ends){setError("Name, start and end times are required.");return}if(new Date(ends)<=new Date(starts)){setError("The event must end after it starts.");return}setBusy(true);const{data:event,error:createError}=await supabase.from("events").insert({name,venue,description,event_type:type,starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),organizer_id:user.id,is_public:isPublic,discovery_radius_m:Number(radius)}).select().single();if(createError||!event){setError(createError?.message??"Could not create event.");setBusy(false);return}if(cover){const ext=cover.name.split(".").pop()??"jpg";const path=`${event.id}/cover.${ext}`;const{error:uploadError}=await supabase.storage.from("event-covers").upload(path,cover,{upsert:true});if(!uploadError)await supabase.from("events").update({cover_path:path}).eq("id",event.id)}await supabase.from("event_participants").insert({event_id:event.id,user_id:user.id});window.location.href=`/events/${event.id}`}
return <AppShell><div className="pb-10 pt-6"><a href="/events" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Events</a><p className="mt-8 text-xs uppercase text-signal">Create a SYNC Zone</p><h1 className="mt-3 text-4xl font-medium">Bring the right people together.</h1><div className="mt-8 space-y-5 rounded-2xl border border-border bg-card p-5"><Field label="Event name"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Designers at the coffee bar"/></Field><Field label="Description"><Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What should people know?"/></Field><Field label="Venue"><Input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Venue or meeting point"/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Starts"><Input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></Field><Field label="Ends"><Input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)}/></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Event type"><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="community">Community</SelectItem><SelectItem value="conference">Conference</SelectItem><SelectItem value="learning">Learning</SelectItem><SelectItem value="social">Social</SelectItem><SelectItem value="sports">Sports</SelectItem></SelectContent></Select></Field><Field label="SYNC radius"><Select value={radius} onValueChange={setRadius}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="100">100 metres</SelectItem><SelectItem value="200">200 metres</SelectItem><SelectItem value="500">500 metres</SelectItem><SelectItem value="1000">1 kilometre</SelectItem></SelectContent></Select></Field></div><Field label="Optional cover image"><label className="flex min-h-24 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-border text-sm text-muted-foreground"><ImagePlus className="h-4 w-4"/>{cover?cover.name:"Choose image"}<input type="file" accept="image/*" className="hidden" onChange={e=>setCover(e.target.files?.[0]??null)}/></label></Field><label className="flex items-center justify-between"><span><strong className="text-sm font-medium">Public event</strong><span className="mt-1 block text-xs text-muted-foreground">Visible to all signed-in SYNC members.</span></span><Switch checked={isPublic} onCheckedChange={setPublic}/></label>{error?<p className="text-sm text-destructive">{error}</p>:null}<Button className="w-full" size="lg" disabled={busy} onClick={create}>{busy?"Creating…":"Create Event"}</Button></div></div></AppShell>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
