import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ChevronRight, MessageCircle } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { getRevealedProfile } from "@/lib/sync.functions";
export const Route=createFileRoute("/_authenticated/connections/")({head:()=>({meta:[{title:"Connections — SYNC"},{name:"description",content:"Message and manage the people you mutually chose to meet."},{property:"og:title",content:"Connections — SYNC"},{property:"og:description",content:"Your private mutual SYNC connections."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Connections});
type Item={connection:Tables<"connections">;profile:Tables<"profiles">;photo:string|null;conversationId:string|null};
function Connections(){const {user}=Route.useRouteContext();const [items,setItems]=useState<Item[]>([]);useEffect(()=>{(async()=>{const {data}=await supabase.from("connections").select("*").or(`user_a_id.eq.${user.id},user_b_id.eq.${user.id}`).order("connected_at",{ascending:false});const all:Item[]=[];for(const c of data??[]){const id=c.user_a_id===user.id?c.user_b_id:c.user_a_id;try{const [revealed,conversation]=await Promise.all([getRevealedProfile({data:{userId:id}}),supabase.from("conversations").select("id").eq("connection_id",c.id).maybeSingle()]);all.push({connection:c,profile:revealed.profile,photo:revealed.photoUrl,conversationId:conversation.data?.id??null})}catch{continue}}setItems(all)})()},[user.id]);return <AppShell light><div className="pt-10"><p className="text-xs uppercase text-muted-foreground">People</p><h1 className="mt-3 text-4xl font-medium">Connections</h1><p className="mt-3 text-sm text-muted-foreground">People you mutually chose to meet.</p>{items.length?<div className="mt-8 grid gap-3 sm:grid-cols-2">{items.map(({connection,profile,photo,conversationId})=><article key={connection.id} className="rounded-2xl border border-border bg-card p-4"><a href={`/connections/${connection.id}`} className="flex items-center gap-4">{photo?<img src={photo} alt="" className="h-16 w-16 rounded-full object-cover"/>:<div className="flex h-16 w-16 items-center justify-center rounded-full bg-secondary text-xl">{profile.name.slice(0,1)}</div>}<div className="min-w-0 flex-1"><h2 className="font-medium">{profile.name}</h2><p className="mt-1 truncate text-sm text-muted-foreground">{connection.context??connection.match_reason}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground"/></a><div className="mt-4 grid grid-cols-2 gap-2"><Button asChild variant="outline" size="sm"><a href={`/connections/${connection.id}`}>Profile</a></Button>{conversationId?<Button asChild size="sm"><a href={`/chat/${conversationId}`}><MessageCircle/>Message</a></Button>:null}</div></article>)}</div>:<div className="mt-28 text-center"><p className="text-xl">Your first SYNC is still out there.</p><p className="mt-3 text-sm text-muted-foreground">Real connections appear here after mutual consent.</p><Button asChild className="mt-8"><a href="/sync">Start Syncing</a></Button></div>}</div></AppShell>}
