import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, MapPin, Plus, UsersRound } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
export const Route=createFileRoute("/_authenticated/events/")({component:Events});
function Events(){const{user}=Route.useRouteContext();const[events,setEvents]=useState<Tables<"events">[]>([]);const[joined,setJoined]=useState<string[]>([]);const[counts,setCounts]=useState<Record<string,number>>({});useEffect(()=>{(async()=>{const [{data:e},{data:p},{data:all}]=await Promise.all([supabase.from("events").select("*").gte("ends_at",new Date().toISOString()).order("starts_at"),supabase.from("event_participants").select("event_id").eq("user_id",user.id),supabase.from("event_participants").select("event_id")]);setEvents(e??[]);setJoined((p??[]).map(x=>x.event_id));setCounts((all??[]).reduce<Record<string,number>>((acc,x)=>({...acc,[x.event_id]:(acc[x.event_id]??0)+1}),{}))})()},[user.id]);const upcoming=events.filter(e=>e.status==="active"&&e.organizer_id!==user.id);const mine=events.filter(e=>e.organizer_id===user.id);const joinedEvents=useMemo(()=>events.filter(e=>joined.includes(e.id)),[events,joined]);return <AppShell><div className="pt-10"><div className="flex items-end justify-between gap-3"><div><p className="text-xs uppercase text-muted-foreground">SYNC Zones</p><h1 className="mt-3 text-4xl font-medium">Events</h1></div><Button asChild size="sm"><a href="/events/new"><Plus/>Create</a></Button></div><Tabs defaultValue="upcoming" className="mt-8"><TabsList className="grid h-auto w-full grid-cols-3 rounded-full"><TabsTrigger className="rounded-full py-2" value="upcoming">Upcoming</TabsTrigger><TabsTrigger className="rounded-full py-2" value="joined">Joined</TabsTrigger><TabsTrigger className="rounded-full py-2" value="mine">Created</TabsTrigger></TabsList><EventTab value="upcoming" events={upcoming} counts={counts}/><EventTab value="joined" events={joinedEvents} counts={counts}/><EventTab value="mine" events={mine} counts={counts}/></Tabs></div></AppShell>}
function EventTab({value,events,counts}:{value:string;events:Tables<"events">[];counts:Record<string,number>}){return <TabsContent value={value} className="mt-6"><div className="grid gap-3 sm:grid-cols-2">{events.map(e=><a key={e.id} href={`/events/${e.id}`} className="rounded-2xl border border-border bg-card p-5 transition-colors hover:bg-elevated"><p className="text-xs uppercase text-signal">{e.event_type} · {new Date(e.starts_at).toLocaleDateString()}</p><h2 className="mt-3 text-xl">{e.name}</h2><div className="mt-4 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{e.venue||"Venue TBA"}</span><span className="inline-flex items-center gap-1"><UsersRound className="h-3.5 w-3.5"/>{counts[e.id]??0} joined</span></div></a>)}</div>{!events.length?<div className="py-24 text-center text-muted-foreground"><CalendarDays className="mx-auto mb-4 h-6 w-6"/>No events here yet.</div>:null}</TabsContent>}
