import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Camera, Check } from "lucide-react";
import { SyncLogo } from "@/components/brand/sync-logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/onboarding")({ component: Onboarding });
const goals=["BUILD","MEET","LEARN","HELP","EXPLORE"];
function Onboarding(){ const {user}=Route.useRouteContext(); const [step,setStep]=useState(1); const [name,setName]=useState(user.user_metadata?.full_name??""); const [bio,setBio]=useState(""); const [photo,setPhoto]=useState<File|null>(null); const [skills,setSkills]=useState<{id:string,name:string}[]>([]); const [selected,setSelected]=useState<string[]>([]); const [custom,setCustom]=useState(""); const [goal,setGoal]=useState("BUILD"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
useEffect(()=>{supabase.from("skills").select("id,name").order("name").then(({data})=>setSkills(data??[]))},[]);
async function finish(){ if(!name.trim()){setError("Add your name to continue.");setStep(1);return} setBusy(true);setError(""); let avatar_path:string|null=null; if(photo){const ext=photo.name.split(".").pop()??"jpg";avatar_path=`${user.id}/profile.${ext}`;const {error:e}=await supabase.storage.from("profile-photos").upload(avatar_path,photo,{upsert:true});if(e){setError(e.message);setBusy(false);return}} const {error:profileError}=await supabase.from("profiles").upsert({id:user.id,name:name.trim(),bio:bio.trim(),avatar_path,primary_context:goal,onboarding_complete:true}); if(profileError){setError(profileError.message);setBusy(false);return} const chosen=[...selected]; if(custom.trim()){let {data}=await supabase.from("skills").select("id").eq("normalized_name",custom.trim().toLowerCase()).maybeSingle();if(!data){const created=await supabase.from("skills").insert({name:custom.trim()}).select("id").single();data=created.data}if(data)chosen.push(data.id)} await supabase.from("user_skills").delete().eq("user_id",user.id);if(chosen.length)await supabase.from("user_skills").insert([...new Set(chosen)].map(skill_id=>({user_id:user.id,skill_id})));window.location.href="/sync" }
return <main className="min-h-screen bg-background px-5 py-8 text-foreground"><div className="mx-auto max-w-md"><div className="flex items-center justify-between"><SyncLogo className="text-xl"/><span className="text-xs text-muted-foreground">0{step} / 03</span></div>{step===1?<section className="pt-20"><p className="text-xs uppercase text-muted-foreground">Your profile</p><h1 className="mt-3 text-4xl font-medium">Let people know who they’re meeting.</h1><label className="mt-10 flex h-28 w-28 cursor-pointer items-center justify-center overflow-hidden rounded-full bg-secondary text-muted-foreground">{photo?<img src={URL.createObjectURL(photo)} className="h-full w-full object-cover" alt="Profile preview"/>:<Camera/>}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label><Input className="mt-8 h-13 rounded-full bg-card px-5" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><Textarea className="mt-3 min-h-28 rounded-2xl bg-card p-5" placeholder="A short human bio" value={bio} maxLength={400} onChange={e=>setBio(e.target.value)}/></section>:step===2?<section className="pt-20"><p className="text-xs uppercase text-muted-foreground">What you know</p><h1 className="mt-3 text-4xl font-medium">Choose your skills.</h1><div className="mt-10 flex flex-wrap gap-2">{skills.map(s=><button key={s.id} onClick={()=>setSelected(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])} className={`rounded-full border px-4 py-2.5 text-sm ${selected.includes(s.id)?"border-foreground bg-foreground text-background":"border-border"}`}>{s.name}</button>)}</div><Input className="mt-5 h-13 rounded-full px-5" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Add another skill"/></section>:<section className="pt-20"><p className="text-xs uppercase text-muted-foreground">Your intent</p><h1 className="mt-3 text-4xl font-medium">What brings you here?</h1><div className="mt-10 space-y-2">{goals.map(g=><button key={g} onClick={()=>setGoal(g)} className={`flex w-full items-center justify-between rounded-2xl border p-5 text-left ${goal===g?"border-foreground bg-foreground text-background":"border-border bg-card"}`}><span>{g[0]+g.slice(1).toLowerCase()}</span>{goal===g?<Check className="h-4 w-4"/>:null}</button>)}</div></section>} {error?<p className="mt-5 text-sm text-red-500">{error}</p>:null}<div className="mt-10 flex gap-3">{step>1?<Button variant="outline" size="lg" onClick={()=>setStep(step-1)}>Back</Button>:null}<Button size="lg" className="flex-1" disabled={busy} onClick={()=>step<3?setStep(step+1):finish()}>{step<3?"Continue":busy?"Saving…":"Enter SYNC"}</Button></div></div></main>}