import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CalendarDays, Compass, GraduationCap, HandHelping, Hammer, Users } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ProximityField } from "@/components/sync/proximity-field";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { activateSync, stopSync } from "@/lib/sync.functions";

export const Route=createFileRoute("/_authenticated/sync")({component:SyncHome});
const modes=[{id:"BUILD",icon:Hammer,desc:"Find the missing skill"},{id:"MEET",icon:Users,desc:"Meet someone worth knowing"},{id:"LEARN",icon:GraduationCap,desc:"Find someone who can teach"},{id:"HELP",icon:HandHelping,desc:"Offer what you know"},{id:"EXPLORE",icon:Compass,desc:"Leave room for serendipity"},{id:"EVENT",icon:CalendarDays,desc:"Meet within a SYNC Zone"}] as const;
function SyncHome(){const {user}=Route.useRouteContext();const [mode,setMode]=useState<typeof modes[number]["id"]>("BUILD");const [text,setText]=useState("");const [active,setActive]=useState(false);const [intent,setIntent]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>{supabase.from("profiles").select("onboarding_complete,discovery_enabled").eq("id",user.id).maybeSingle().then(({data})=>{if(!data?.onboarding_complete)window.location.href="/onboarding";else setActive(data.discovery_enabled)});supabase.from("intents").select("original_text").eq("user_id",user.id).eq("status","ACTIVE").order("created_at",{ascending:false}).limit(1).maybeSingle().then(({data})=>setIntent(data?.original_text??""))},[user.id]);async function start(){if(text.trim().length<3)return;setBusy(true);await activateSync({data:{text,goal:mode}});setIntent(text);setActive(true);setBusy(false)}async function stop(){await stopSync();setActive(false)}return <AppShell>{active?<section className="flex min-h-[70vh] flex-col items-center justify-center text-center"><ProximityField/><p className="mt-12 text-xs uppercase tracking-[.16em] text-signal">SYNC ACTIVE</p><h1 className="mt-4 text-3xl font-medium">We’ll let you know when someone worth meeting appears.</h1><p className="mt-5 max-w-xs text-sm text-muted-foreground">{intent}</p><a href="/discovery" className="mt-8 inline-flex h-11 items-center rounded-full bg-primary px-6 text-sm text-primary-foreground">Open Discovery</a><Button className="mt-3" variant="dark" onClick={stop}>Stop Syncing</Button></section>:<><p className="mt-10 text-xs uppercase text-muted-foreground">Discovery Off</p><h1 className="mt-4 text-4xl font-medium leading-tight">What are you looking for today?</h1><div className="mt-9 grid grid-cols-2 gap-2">{modes.map(({id,icon:Icon,desc})=><button key={id} onClick={()=>setMode(id)} className={`min-h-32 rounded-2xl border p-4 text-left ${mode===id?"border-signal bg-elevated":"border-border bg-card"}`}><Icon className={mode===id?"h-5 w-5 text-signal":"h-5 w-5"} strokeWidth={1.5}/><span className="mt-5 block text-sm font-medium">{id[0]+id.slice(1).toLowerCase()}</span><span className="mt-1 block text-xs leading-relaxed text-muted-foreground">{desc}</span></button>)}</div><label className="mt-8 block text-sm">Tell SYNC what you need</label><Textarea value={text} maxLength={1000} onChange={e=>setText(e.target.value)} placeholder="I need someone who…" className="mt-3 min-h-32 rounded-2xl bg-card p-5"/><Button size="lg" className="mt-3 w-full" disabled={busy||text.trim().length<3} onClick={start}>{busy?"Starting…":"START SYNCING"}</Button></>}</AppShell>}