import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, MapPin, MessageCircle } from "lucide-react";
import { Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { PromptInput, PromptInputBody, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { getRevealedProfile } from "@/lib/sync.functions";
import { notifyNewMessage } from "@/lib/push.functions";

export const Route = createFileRoute("/_authenticated/chat/$conversationId")({head:()=>({meta:[{title:"Private chat — SYNC"},{name:"description",content:"A private conversation with your mutual SYNC connection."},{property:"og:title",content:"Private chat — SYNC"},{property:"og:description",content:"Messages visible only to mutual SYNC connections."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}), component: Chat });
function Chat(){
  const {user}=Route.useRouteContext(); const {conversationId}=Route.useParams();
  const [messages,setMessages]=useState<Tables<"messages">[]>([]); const [name,setName]=useState("Connection"); const [connectionId,setConnectionId]=useState<string|null>(null); const [sending,setSending]=useState(false); const [problem,setProblem]=useState("");
  const load=useCallback(async()=>{const {data:conversation,error}=await supabase.from("conversations").select("connection_id").eq("id",conversationId).single();if(error||!conversation){setProblem("This conversation is unavailable.");return;}setConnectionId(conversation.connection_id);const {data:connection}=await supabase.from("connections").select("user_a_id,user_b_id").eq("id",conversation.connection_id).single();if(connection){const otherId=connection.user_a_id===user.id?connection.user_b_id:connection.user_a_id;try{const shown=await getRevealedProfile({data:{userId:otherId}});setName(shown.profile.name)}catch{setName("Connection")}}const {data}=await supabase.from("messages").select("*").eq("conversation_id",conversationId).order("created_at");setMessages(data??[]);await supabase.from("messages").update({read_at:new Date().toISOString()}).eq("conversation_id",conversationId).neq("sender_id",user.id).is("read_at",null)},[conversationId,user.id]);
  useEffect(()=>{load();const channel=supabase.channel(`chat:${conversationId}`).on("postgres_changes",{event:"*",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},load).subscribe();return()=>{supabase.removeChannel(channel)}},[conversationId,load]);
  async function send({text}:{text:string}){const content=text.trim();if(!content||sending)return;setSending(true);setProblem("");const {error}=await supabase.from("messages").insert({conversation_id:conversationId,sender_id:user.id,content});setSending(false);if(error){setProblem(error.message);throw error}void notifyNewMessage({data:{conversationId,preview:content.slice(0,160)}}).catch(()=>{});await load()}
  return <main className="dark flex h-dvh flex-col bg-background text-foreground"><header className="flex h-18 shrink-0 items-center justify-between border-b border-border px-4"><a href="/connections" aria-label="Back to connections"><ArrowLeft/></a><div className="text-center"><p className="font-medium">{name}</p><p className="text-xs text-muted-foreground">Private connection</p></div>{connectionId?<a href={`/connections/${connectionId}`} aria-label="Connection details"><MapPin/></a>:<span className="w-6"/>}</header><Conversation className="min-h-0"><ConversationContent className="mx-auto w-full max-w-2xl gap-3 px-4 py-6">{messages.length?messages.map((message)=>{const mine=message.sender_id===user.id;return <div key={message.id} className={`flex ${mine?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${mine?"rounded-br-md bg-primary text-primary-foreground":"rounded-bl-md bg-card"}`}><p className="whitespace-pre-wrap break-words">{message.content}</p><p className={`mt-1 text-[10px] ${mine?"text-ink/55":"text-muted-foreground"}`}>{new Date(message.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}{mine&&message.read_at?" · Read":""}</p></div></div>}):<ConversationEmptyState icon={<MessageCircle/>} title="Start the conversation" description="Only you and this connection can see these messages."/>}</ConversationContent><ConversationScrollButton/></Conversation><footer className="shrink-0 border-t border-border bg-background p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))]"><div className="mx-auto max-w-2xl"><PromptInput onSubmit={send} accept=""><PromptInputBody><PromptInputTextarea name="message" placeholder={`Message ${name}`} className="max-h-36 min-h-12"/></PromptInputBody><PromptInputFooter><span className="px-2 text-[10px] text-muted-foreground">Private and visible only after SYNC</span><PromptInputSubmit status={sending?"submitted":"ready"}/></PromptInputFooter></PromptInput>{problem?<p className="mt-2 text-xs text-destructive">{problem}</p>:null}</div></footer></main>
}
